#############################################################################
# Makefile for building: COMDoubler
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  COMDoubler.pro
# Template: app
# Command: /home/jivilkov/tools/qt5.8.0/5.8/gcc_64/bin/qmake -o Makefile COMDoubler.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /home/jivilkov/tools/qt5.8.0/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = COMDoubler1.0.0
DISTDIR = /media/jivilkov/Новый\ том/projects/com_doubler/.tmp/COMDoubler1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5SerialPort -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		COMDoubler.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = COMDoubler
DESTDIR       = 
TARGET        = COMDoubler


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: COMDoubler.pro /home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf /home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf \
		COMDoubler.pro \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib/libQt5Widgets.prl \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib/libQt5Gui.prl \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib/libQt5SerialPort.prl \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile COMDoubler.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/spec_pre.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/unix.conf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/linux.conf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/sanitize.conf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base.conf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/g++-base.conf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/common/g++-unix.conf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/qconfig.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qt_functions.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qt_config.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/toolchain.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/default_pre.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/resolve_config.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/default_post.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qml_debug.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/warn_on.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qt.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/resources.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/moc.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/unix/opengl.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/uic.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/unix/thread.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/qmake_use.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/file_copies.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/exceptions.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/yacc.prf:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/lex.prf:
COMDoubler.pro:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib/libQt5Widgets.prl:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib/libQt5Gui.prl:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib/libQt5SerialPort.prl:
/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile COMDoubler.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QMainWindow \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qicon.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/QSerialPort \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/qserialport.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/qserialportglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/QSerialPortInfo \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/qserialportinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QMessageBox \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qmessagebox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qdialog.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QComboBox \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qcombobox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qstyleoption.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qvalidator.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qregularexpression.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qslider.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qstyle.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabbar.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qrubberband.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qframe.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/QTime \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qdatetime.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/QTimer \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtimer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbasictimer.h \
		mainwindow.h \
		moc_predefs.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/bin/moc
	/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/mkspecs/linux-g++ -I'/media/jivilkov/Новый том/projects/com_doubler' -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort -I/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/bin/uic
	/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QMainWindow \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qicon.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/QSerialPort \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/qserialport.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/qserialportglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/QSerialPortInfo \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/qserialportinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QMessageBox \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qmessagebox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qdialog.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QComboBox \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qcombobox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qstyleoption.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qvalidator.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qregularexpression.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qslider.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qstyle.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabbar.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qrubberband.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qframe.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/QTime \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qdatetime.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/QTimer \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtimer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbasictimer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QApplication \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qapplication.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qeventloop.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qguiapplication.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QMainWindow \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qconfig.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtcore-config.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsysinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qlogging.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qflags.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtypetraits.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmutex.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qnumeric.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qversiontagging.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtgui-config.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qwidget.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qnamespace.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobject.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstring.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qchar.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbytearray.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qrefcount.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qarraydata.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qlist.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qalgorithms.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qiterator.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qpair.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstringlist.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qregexp.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcoreevent.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmetatype.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qobject_impl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmargins.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qrect.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsize.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qpoint.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpalette.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qcolor.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qrgb.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qrgba64.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qbrush.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qvector.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qmatrix.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpolygon.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qregion.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qdatastream.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qiodevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qline.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtransform.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpainterpath.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qimage.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpixelformat.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpixmap.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qshareddata.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qhash.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfont.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfontinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qcursor.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qkeysequence.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qevent.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qvariant.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qmap.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qdebug.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtextstream.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qlocale.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qset.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qurl.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qurlquery.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qfile.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qfiledevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qvector2d.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qicon.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/QSerialPort \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/qserialport.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/qserialportglobal.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/QSerialPortInfo \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtSerialPort/qserialportinfo.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QMessageBox \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qmessagebox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qdialog.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QComboBox \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qcombobox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qstyleoption.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qvalidator.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qregularexpression.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qslider.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractslider.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qstyle.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtabbar.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qrubberband.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qframe.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qabstractitemmodel.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/QTime \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qdatetime.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/QTimer \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qtimer.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qbasictimer.h \
		ui_mainwindow.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/QVariant \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QAction \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qaction.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qactiongroup.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QApplication \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qapplication.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qeventloop.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qguiapplication.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qinputmethod.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QButtonGroup \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qbuttongroup.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QGridLayout \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qlayout.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QGroupBox \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qgroupbox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QHBoxLayout \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QHeaderView \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qheaderview.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractitemview.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/qitemselectionmodel.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QLabel \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qlabel.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QPlainTextEdit \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qplaintextedit.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qtextedit.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtextdocument.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtextoption.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtextcursor.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtextformat.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qpen.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qtextlayout.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qglyphrun.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qrawfont.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtGui/qfontdatabase.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QPushButton \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qpushbutton.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qabstractbutton.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QSpacerItem \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QSpinBox \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qspinbox.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QStatusBar \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/qstatusbar.h \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtWidgets/QWidget \
		/home/jivilkov/tools/qt5.8.0/5.8/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/COMDoubler/bin || mkdir -p $(INSTALL_ROOT)/opt/COMDoubler/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/COMDoubler/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/COMDoubler/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/COMDoubler/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

